/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Hamid Akbari Ghannad
 */
public class LoanCalculator extends javax.swing.JFrame {

    private Loan l = new Loan(1000, 36, 10);
    
    /**
     * Creates new form LoanCalculator
     */
    public LoanCalculator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        spnPrincipal = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        spnDuration = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        spnAnnualInterestRate = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        txtMonthlyPayment = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtTotalPayment = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtTotalInterest = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Loan Calculator");
        setMinimumSize(new java.awt.Dimension(460, 280));
        setResizable(false);
        setSize(new java.awt.Dimension(0, 0));
        getContentPane().setLayout(new java.awt.GridLayout(7, 2, 10, 10));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Loan Principal Amount");
        getContentPane().add(jLabel1);

        spnPrincipal.setModel(new javax.swing.SpinnerNumberModel(1000.0d, 0.0d, null, 100.0d));
        spnPrincipal.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spnPrincipalStateChanged(evt);
            }
        });
        getContentPane().add(spnPrincipal);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Duration (Months)");
        getContentPane().add(jLabel2);

        spnDuration.setModel(new javax.swing.SpinnerNumberModel(36, 6, 240, 1));
        spnDuration.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spnDurationStateChanged(evt);
            }
        });
        getContentPane().add(spnDuration);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Annual Interest Rate");
        getContentPane().add(jLabel3);

        spnAnnualInterestRate.setModel(new javax.swing.SpinnerNumberModel(10.0d, 0.0d, 100.0d, 0.1d));
        spnAnnualInterestRate.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spnAnnualInterestRateStateChanged(evt);
            }
        });
        getContentPane().add(spnAnnualInterestRate);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Monthly Payment");
        getContentPane().add(jLabel4);

        txtMonthlyPayment.setEditable(false);
        getContentPane().add(txtMonthlyPayment);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Total Payment");
        getContentPane().add(jLabel5);

        txtTotalPayment.setEditable(false);
        getContentPane().add(txtTotalPayment);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Total Interest");
        getContentPane().add(jLabel6);

        txtTotalInterest.setEditable(false);
        getContentPane().add(txtTotalInterest);

        jButton1.setText("Calculate");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        /* Loan l = new Loan(
                (double)spnPrincipal.getValue(), 
                (int)spnDuration.getValue(), 
                (double)spnAnnualInterestRate.getValue()
        ); */
        this.l.setPrincipal((double)spnPrincipal.getValue());
        this.l.setDuration((int)spnDuration.getValue());
        this.l.setAnnualInterestRate((double)spnAnnualInterestRate.getValue());
        
        txtMonthlyPayment.setText(String.valueOf(l.getMonthlyPayment()));
        txtTotalPayment.setText(String.valueOf(l.getTotalPayment()));
        txtTotalInterest.setText(String.valueOf(l.getTotalInterest()));
    }//GEN-LAST:event_jButton1ActionPerformed

    private void spnPrincipalStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spnPrincipalStateChanged
        jButton1ActionPerformed(null);
    }//GEN-LAST:event_spnPrincipalStateChanged

    private void spnDurationStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spnDurationStateChanged
        jButton1ActionPerformed(null);
    }//GEN-LAST:event_spnDurationStateChanged

    private void spnAnnualInterestRateStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spnAnnualInterestRateStateChanged
        jButton1ActionPerformed(null);
    }//GEN-LAST:event_spnAnnualInterestRateStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoanCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoanCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoanCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoanCalculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoanCalculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JSpinner spnAnnualInterestRate;
    private javax.swing.JSpinner spnDuration;
    private javax.swing.JSpinner spnPrincipal;
    private javax.swing.JTextField txtMonthlyPayment;
    private javax.swing.JTextField txtTotalInterest;
    private javax.swing.JTextField txtTotalPayment;
    // End of variables declaration//GEN-END:variables
}
